/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/catalog/new` | `/catalog/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/appearance` | `/profile/appearance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/payout` | `/profile/payout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/storefront` | `/profile/storefront`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/catalog/[id]` | `/catalog/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/catalog` | `/catalog`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/catalog/new` | `/catalog/new`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile/appearance` | `/profile/appearance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile/payout` | `/profile/payout`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile/storefront` | `/profile/storefront`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/catalog/[id]` | `/catalog/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(main)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/catalog${`?${string}` | `#${string}` | ''}` | `/catalog${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/catalog/new${`?${string}` | `#${string}` | ''}` | `/catalog/new${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile/appearance${`?${string}` | `#${string}` | ''}` | `/profile/appearance${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile/edit${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile/payout${`?${string}` | `#${string}` | ''}` | `/profile/payout${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile/storefront${`?${string}` | `#${string}` | ''}` | `/profile/storefront${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/catalog/new` | `/catalog/new`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/appearance` | `/profile/appearance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/payout` | `/profile/payout`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile/storefront` | `/profile/storefront`; params?: Router.UnknownInputParams; } | `${'/(main)'}/catalog/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/catalog/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(main)'}/catalog/[id]` | `/catalog/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(main)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
