events {
    worker_connections 1024;
}

http {
    upstream web-customer { server web-customer:3000; }
    upstream web-vendor   { server web-vendor:3000; }
    upstream web-admin    { server web-admin:3000; }
    upstream web-hub      { server web-hub:3000; }
    upstream web-rider    { server web-rider:3000; }
    upstream api          { server api:8000; }

    server {
        listen 80;
        server_name avdanstore.com www.avdanstore.com;
        location / { proxy_pass http://web-customer; proxy_set_header Host $host; }
    }

    server {
        listen 80;
        server_name vendor.avdanstore.com;
        location / { proxy_pass http://web-vendor; proxy_set_header Host $host; }
    }

    server {
        listen 80;
        server_name admin.avdanstore.com;
        location / { proxy_pass http://web-admin; proxy_set_header Host $host; }
    }

    server {
        listen 80;
        server_name hub.avdanstore.com;
        location / { proxy_pass http://web-hub; proxy_set_header Host $host; }
    }

    server {
        listen 80;
        server_name rider.avdanstore.com;
        location / { proxy_pass http://web-rider; proxy_set_header Host $host; }
    }

    server {
        listen 80;
        server_name api.avdanstore.com;
        location / { proxy_pass http://api; proxy_set_header Host $host; }
    }
}
